name: Build and Release Flutter App

on: push

jobs:
    build-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: "3.7.11"

            - name: Install dependencies
              run: flutter pub get

            - name: Build APK for Android
              run: flutter build apk --release

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: "zip"
                  filename: CO2App-${{github.ref_name}}-android.zip
                  directory: build/app/outputs/flutter-apk/

            - name: Android Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
              with:
                  files: build/app/outputs/flutter-apk/CO2App-${{github.ref_name}}-android.zip

    build-linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: "3.7.11"

            - name: Install dependencies
              run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

            - name: Install project dependencies
              run: flutter pub get

            - name: Generate intermediates
              run: flutter pub run build_runner build --delete-conflicting-outputs

            - name: Enable linux build
              run: flutter config --enable-linux-desktop

            - name: Build artifacts
              run: flutter build linux --release

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: "zip"
                  filename: CO2App-${{github.ref_name}}-linux.zip
                  directory: build/linux/x64/release/bundle

            - name: Linux Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
              with:
                  files: build/linux/x64/release/bundle/CO2App-${{github.ref_name}}-linux.zip

    build-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "17"

            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: "3.7.11"

            - name: Install project dependencies
              run: flutter pub get

            - name: Enable windows build
              run: flutter config --enable-windows-desktop

            - name: Build artifacts
              run: flutter build windows --release

            - name: Archive Release
              uses: thedoctor0/zip-release@master
              with:
                  type: "zip"
                  filename: CO2App-${{github.ref_name}}-windows.zip
                  directory: build/windows/runner/Release

            - name: Windows Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
              with:
                  files: build/windows/runner/Release/CO2App-${{github.ref_name}}-windows.zip
