name: Build and Release Flutter App

on:
    push:
        branches:
            - main

jobs:
    build_and_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: "3.7.11"

            - name: Enable desktop support for Linux
              run: flutter config --enable-linux-desktop

            - name: Enable desktop support for Windows
              run: flutter config --enable-windows-desktop

            - name: Build app for Linux, Windows, and Android
              run: flutter build linux windows apk

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
              with:
                  tag_name: v0.1.0
                  release_name: Release v0.1.0
                  body: "First release"
                  draft: false
                  prerelease: false

            - name: Upload Linux app
              uses: actions/upload-artifact@v2
              with:
                  name: linux
                  path: build/linux

            - name: Upload Windows app
              uses: actions/upload-artifact@v2
              with:
                  name: windows
                  path: build/windows

            - name: Upload Android app
              uses: actions/upload-artifact@v2
              with:
                  name: apk
                  path: build/app/outputs/flutter-apk/app-release.apk
