name: Build and Release Flutter App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.7.11"

            - name: Install dependencies
              run: flutter pub get

            - name: Build Linux
              run: flutter build linux

            - name: Build APK
              run: flutter build apk

            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                  java-version: "12.x"

            - name: Build Windows
              run: flutter build windows

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files:
                      - build/linux/release/bundle.tar.gz
                      - build/app/outputs/flutter-apk/app-release.apk
                      - build/windows/runner/Release/runner.exe
                  tag_name: ${{ github.ref }}
                  title: Release ${{ github.ref }}
                  body: Automated release created by GitHub Actions
              env:
                  GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
