name: Flutter CI

on:
    push:
        branches:
            - main

jobs:
    build-and-release-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v2
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-cache-
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev
            - run: flutter config --enable-linux-desktop
            - run: flutter build linux
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes in this Release
                  draft: false
                  prerelease: false

    build-and-release-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v2
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-cache-
            - uses: subosito/flutter-action@v2
              with:
                  channel: "beta"
            - run: flutter config --enable-windows-desktop
            - run: flutter build windows
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes in this Release
                  draft: false
                  prerelease: false

    build-and-release-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v2
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pub-cache-
            - uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "11"
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
            - run: flutter pub get
            - run: flutter build apk
            - run: flutter build appbundle
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes in this Release
                  draft: false
                  prerelease: false
